package ua.ulch.artshop.presentation.ui.common

enum class SubcategoryId(val id: Int) {
    FAVOURITE_CATEGORY_ID(-100),
    HOLIDAYS_CATEGORY_ID(-10),
    DIFFERENT_CATEGORY_ID(-20),
    SIGNIFICANT_CATEGORY_ID(-30),
    EVERYDAY_CATEGORY_ID(-40),
    BIRTHDAY_CATEGORY_ID(21),
    PROFESSIONAL_CATEGORY_ID(41),
}

enum class SubcategoryIdEn(val id: Int) {
    FAVOURITE_CATEGORY_ID(-100),
    BIRTHDAY_CATEGORY_ID(110),
    EVERYDAY_CATEGORY_ID(114),
    THANK_YOU_CATEGORY_ID(129),
    ROMANTIC_CATEGORY_ID(135),
    QUOTES_CATEGORY_ID(127),
    FRIENDSHIP_CATEGORY_ID(171)
}
